package arrange;

import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;

import java.net.MalformedURLException;
import java.net.URL;

/**
 * Package: arrange
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 22.04.2018 2018
 */
public class AppStartStop {
    public static AppiumDriver<WebElement> appiumDriver = null;
    public static AppiumDriver startApp(String appUrl, String deviceName) throws MalformedURLException {
        DesiredCapabilities cap = new DesiredCapabilities();
        cap.setCapability(MobileCapabilityType.DEVICE_NAME, deviceName);
        cap.setCapability(MobileCapabilityType.APP, appUrl);
        cap.setCapability("avd", deviceName);
        appiumDriver = new AndroidDriver<WebElement>(new URL("http://localhost:4723/wd/hub"),cap);

        return appiumDriver;
    }
    public static void appStop(){
        if(appiumDriver !=null){
            appiumDriver.close();
            appiumDriver.quit();
        }
    }
}
