package assertion;

import arrange.AppStartStop;
import com.sun.org.apache.bcel.internal.generic.NEW;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.Assert;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;

/**
 * Package: PACKAGE_NAME
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.04.2018 2018
 */
public class MessageTest {
    AppiumDriver<WebElement> appiumDriver;

    @BeforeClass
    public void setUp() throws MalformedURLException {

        String appUrl = "C:\\Users\\Hoang.Son.Nguyen\\OneDrive - Nagarro\\AppiumMaven\\TestApp\\Beispiel für Brief schreiben_v1.0_apkpure.com.apk";
        String deviceName = "Pixel_XL_API_22";
        appiumDriver = AppStartStop.startApp(appUrl, deviceName);
        try {
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }


    }

    @Test
    public void fistMessage() {
        Assert.assertNotNull(appiumDriver.getContext());
        WebElement element = appiumDriver.findElement(By.id("text_list"));
        //System.out.println(element.getAttribute("id"));
        element.click();

    }
}
