import com.sun.org.apache.bcel.internal.generic.NEW;
import io.appium.java_client.AppiumDriver;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.remote.MobileCapabilityType;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.net.MalformedURLException;
import java.net.URL;

/**
 * Package: PACKAGE_NAME
 * Generated by: Hoang.Son.Nguyen
 * Generated at: 19.04.2018 2018
 */
public class FirstAppiumTest {
    AppiumDriver<WebElement> appiumDriver;

    @BeforeClass
    public void setUp() throws MalformedURLException {
        DesiredCapabilities cap = new DesiredCapabilities();
        cap.setCapability(MobileCapabilityType.DEVICE_NAME, "Pixel_XL_API_22");
        cap.setCapability(MobileCapabilityType.APP, "C:\\Users\\Hoang.Son.Nguyen\\OneDrive - Nagarro\\AppiumMaven\\TestApp\\Beispiel für Brief schreiben_v1.0_apkpure.com.apk");
        cap.setCapability("avd", "Pixel_XL_API_22");
        //appiumDriver = new AndroidDriver<WebElement>(new URL("http://127.0.0.1:4723"),cap);
        appiumDriver = new AndroidDriver<WebElement>(new URL("http://localhost:4723/wd/hub"),cap);
    }

    @Test
    public void fistTest() {

    }
}
